/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './utils/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        'playfair': ['Playfair Display', 'serif'],
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
      },
    },
  },
  plugins: [],
  // Ensure all classes are included in production
  safelist: [
    // Status colors
    'bg-green-500',
    'bg-red-500', 
    'bg-yellow-500',
    'bg-green-600',
    'bg-red-600',
    'bg-yellow-600',
    'text-green-600',
    'text-red-600',
    'text-yellow-600',
    'text-green-800',
    'text-red-800',
    'text-yellow-800',
    'bg-green-100',
    'bg-red-100',
    'bg-yellow-100',
    // Purple variations
    'bg-purple-600',
    'bg-purple-700',
    'bg-purple-800',
    'bg-purple-900',
    'hover:bg-purple-600',
    'hover:bg-purple-700',
    'hover:bg-purple-800',
    'hover:bg-purple-900',
    'text-purple-600',
    'text-purple-700',
    'text-purple-900',
    // Common utility classes
    'rounded-full',
    'rounded-md',
    'rounded-lg',
    'shadow-sm',
    'shadow-md',
    'border',
    'border-gray-200',
    'border-gray-300',
    'hover:shadow-lg',
    'transition',
    'duration-200',
    // Grid and flex classes
    'grid-cols-1',
    'grid-cols-2', 
    'grid-cols-3',
    'grid-cols-4',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'flex-col',
    'flex-row',
    'md:flex-row',
    'sm:flex-row',
    // Text and spacing
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'px-2',
    'px-3',
    'px-4',
    'py-1',
    'py-2',
    'py-4',
    'py-6',
    'py-8',
    'mb-2',
    'mb-3',
    'mb-4',
    'mb-6',
    'gap-2',
    'gap-4',
    'gap-6',
    // Width classes
    'w-4',
    'w-16',
    'w-full',
    'md:w-48',
    'max-w-6xl',
    // Height classes
    'h-2',
    'h-4',
    'min-h-screen',
  ]
}
